"""Parsers turn raw KIS payloads into normalized models from `kis.models`."""

from __future__ import annotations

from kis.parsers.rest import (
    date_value,
    decimal_or_none,
    format_date,
    int_or_none,
    optional_decimal,
    output_dict,
    output_rows,
    parse_date,
    parse_domestic_current_price,
    parse_domestic_ohlcv_bar,
    parse_domestic_volume_rank_item,
    parse_financial_summary,
    parse_investor_flow,
    parse_minute_datetime,
    parse_overseas_current_price,
    parse_overseas_minute_bar,
    parse_overseas_ohlcv_bar,
    parse_overseas_volume_surge_item,
    parse_product_info,
    required_decimal,
    required_int,
    time_value,
)
from kis.parsers.realtime import (
    parse_orderbook_payload,
    parse_realtime_frame,
    parse_realtime_frame_header,
    parse_trade_payload,
)

__all__ = [
    "date_value",
    "decimal_or_none",
    "format_date",
    "int_or_none",
    "optional_decimal",
    "output_dict",
    "output_rows",
    "parse_date",
    "parse_domestic_current_price",
    "parse_domestic_ohlcv_bar",
    "parse_domestic_volume_rank_item",
    "parse_financial_summary",
    "parse_investor_flow",
    "parse_minute_datetime",
    "parse_overseas_current_price",
    "parse_overseas_minute_bar",
    "parse_overseas_ohlcv_bar",
    "parse_overseas_volume_surge_item",
    "parse_product_info",
    "parse_orderbook_payload",
    "parse_realtime_frame",
    "parse_realtime_frame_header",
    "parse_trade_payload",
    "required_decimal",
    "required_int",
    "time_value",
]
