"""EndpointSpec registry for `[국내주식] 시세분석.xlsx`."""

from __future__ import annotations

from kis.endpoints.registry import EndpointSpec, register

# Each tuple keeps the source workbook row API 명 in the final field.
_SPECS = (
    (
        "domestic.analysis.psearch_title",
        "/uapi/domestic-stock/v1/quotations/psearch-title",
        "HHKST03900300",
        None,
        (),
        "종목조건검색 목록조회",
    ),
    (
        "domestic.analysis.psearch_result",
        "/uapi/domestic-stock/v1/quotations/psearch-result",
        "HHKST03900400",
        None,
        ("seq",),
        "종목조건검색조회",
    ),
    (
        "domestic.analysis.intstock_grouplist",
        "/uapi/domestic-stock/v1/quotations/intstock-grouplist",
        "HHKCM113004C7",
        None,
        ("FID_ETC_CLS_CODE", "USER_ID"),
        "관심종목 그룹조회",
    ),
    (
        "domestic.analysis.intstock_multprice",
        "/uapi/domestic-stock/v1/quotations/intstock-multprice",
        "FHKST11300006",
        None,
        (
            "FID_INPUT_ISCD_1",
            "FID_COND_MRKT_DIV_CODE_2",
            "FID_INPUT_ISCD_2",
            "FID_COND_MRKT_DIV_CODE_3",
            "FID_INPUT_ISCD_3",
            "FID_COND_MRKT_DIV_CODE_4",
            "FID_INPUT_ISCD_4",
            "FID_COND_MRKT_DIV_CODE_5",
            "FID_INPUT_ISCD_5",
            "FID_COND_MRKT_DIV_CODE_6",
            "FID_INPUT_ISCD_6",
            "FID_COND_MRKT_DIV_CODE_7",
            "FID_INPUT_ISCD_7",
            "FID_COND_MRKT_DIV_CODE_8",
            "FID_INPUT_ISCD_8",
            "FID_COND_MRKT_DIV_CODE_9",
            "FID_INPUT_ISCD_9",
            "FID_COND_MRKT_DIV_CODE_10",
            "FID_INPUT_ISCD_10",
            "FID_COND_MRKT_DIV_CODE_11",
            "FID_INPUT_ISCD_11",
            "FID_COND_MRKT_DIV_CODE_12",
            "FID_INPUT_ISCD_12",
            "FID_COND_MRKT_DIV_CODE_13",
            "FID_INPUT_ISCD_13",
            "FID_COND_MRKT_DIV_CODE_14",
            "FID_INPUT_ISCD_14",
            "FID_COND_MRKT_DIV_CODE_15",
            "FID_INPUT_ISCD_15",
            "FID_COND_MRKT_DIV_CODE_16",
            "FID_INPUT_ISCD_16",
            "FID_COND_MRKT_DIV_CODE_17",
            "FID_INPUT_ISCD_17",
            "FID_COND_MRKT_DIV_CODE_18",
            "FID_INPUT_ISCD_18",
            "FID_COND_MRKT_DIV_CODE_19",
            "FID_INPUT_ISCD_19",
            "FID_COND_MRKT_DIV_CODE_20",
            "FID_INPUT_ISCD_20",
            "FID_COND_MRKT_DIV_CODE_21",
            "FID_INPUT_ISCD_21",
            "FID_COND_MRKT_DIV_CODE_22",
            "FID_INPUT_ISCD_22",
            "FID_COND_MRKT_DIV_CODE_23",
            "FID_INPUT_ISCD_23",
            "FID_COND_MRKT_DIV_CODE_24",
            "FID_INPUT_ISCD_24",
            "FID_COND_MRKT_DIV_CODE_25",
            "FID_INPUT_ISCD_25",
            "FID_COND_MRKT_DIV_CODE_26",
            "FID_INPUT_ISCD_26",
            "FID_COND_MRKT_DIV_CODE_27",
            "FID_INPUT_ISCD_27",
            "FID_COND_MRKT_DIV_CODE_28",
            "FID_INPUT_ISCD_28",
            "FID_COND_MRKT_DIV_CODE_29",
            "FID_INPUT_ISCD_29",
            "FID_COND_MRKT_DIV_CODE_30",
            "FID_INPUT_ISCD_30",
        ),
        "관심종목(멀티종목) 시세조회",
    ),
    (
        "domestic.analysis.intstock_stocklist_by_group",
        "/uapi/domestic-stock/v1/quotations/intstock-stocklist-by-group",
        "HHKCM113004C6",
        None,
        (
            "USER_ID",
            "DATA_RANK",
            "INTER_GRP_CODE",
            "INTER_GRP_NAME",
            "HTS_KOR_ISNM",
            "CNTG_CLS_CODE",
            "FID_ETC_CLS_CODE",
        ),
        "관심종목 그룹별 종목조회",
    ),
    (
        "domestic.analysis.foreign_institution_total",
        "/uapi/domestic-stock/v1/quotations/foreign-institution-total",
        "FHPTJ04400000",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_DIV_CLS_CODE",
            "FID_RANK_SORT_CLS_CODE",
            "FID_ETC_CLS_CODE",
        ),
        "국내기관_외국인 매매종목가집계",
    ),
    (
        "domestic.analysis.frgnmem_trade_estimate",
        "/uapi/domestic-stock/v1/quotations/frgnmem-trade-estimate",
        "FHKST644100C0",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_RANK_SORT_CLS_CODE",
            "FID_RANK_SORT_CLS_CODE_2",
        ),
        "외국계 매매종목 가집계",
    ),
    (
        "domestic.analysis.investor_trade_by_stock_daily",
        "/uapi/domestic-stock/v1/quotations/investor-trade-by-stock-daily",
        "FHPTJ04160001",
        None,
        ("FID_INPUT_ISCD", "FID_INPUT_DATE_1", "FID_ORG_ADJ_PRC", "FID_ETC_CLS_CODE"),
        "종목별 투자자매매동향(일별)",
    ),
    (
        "domestic.analysis.inquire_investor_time_by_market",
        "/uapi/domestic-stock/v1/quotations/inquire-investor-time-by-market",
        "FHPTJ04030000",
        None,
        ("fid_input_iscd_2",),
        "시장별 투자자매매동향(시세)",
    ),
    (
        "domestic.analysis.inquire_investor_daily_by_market",
        "/uapi/domestic-stock/v1/quotations/inquire-investor-daily-by-market",
        "FHPTJ04040000",
        None,
        (
            "FID_INPUT_ISCD",
            "FID_INPUT_DATE_1",
            "FID_INPUT_ISCD_1",
            "FID_INPUT_DATE_2",
            "FID_INPUT_ISCD_2",
        ),
        "시장별 투자자매매동향(일별)",
    ),
    (
        "domestic.analysis.frgnmem_pchs_trend",
        "/uapi/domestic-stock/v1/quotations/frgnmem-pchs-trend",
        "FHKST644400C0",
        None,
        ("FID_INPUT_ISCD_2", "FID_COND_MRKT_DIV_CODE"),
        "종목별 외국계 순매수추이",
    ),
    (
        "domestic.analysis.frgnmem_trade_trend",
        "/uapi/domestic-stock/v1/quotations/frgnmem-trade-trend",
        "FHPST04320000",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_INPUT_ISCD_2",
            "FID_MRKT_CLS_CODE",
            "FID_VOL_CNT",
        ),
        "회원사 실시간 매매동향(틱)",
    ),
    (
        "domestic.analysis.inquire_member_daily",
        "/uapi/domestic-stock/v1/quotations/inquire-member-daily",
        "FHPST04540000",
        None,
        (
            "FID_INPUT_ISCD",
            "FID_INPUT_ISCD_2",
            "FID_INPUT_DATE_1",
            "FID_INPUT_DATE_2",
            "FID_SCTN_CLS_CODE",
        ),
        "주식현재가 회원사 종목매매동향",
    ),
    (
        "domestic.analysis.program_trade_by_stock",
        "/uapi/domestic-stock/v1/quotations/program-trade-by-stock",
        "FHPPG04650101",
        None,
        ("FID_INPUT_ISCD",),
        "종목별 프로그램매매추이(체결)",
    ),
    (
        "domestic.analysis.program_trade_by_stock_daily",
        "/uapi/domestic-stock/v1/quotations/program-trade-by-stock-daily",
        "FHPPG04650201",
        None,
        ("FID_INPUT_ISCD", "FID_INPUT_DATE_1"),
        "종목별 프로그램매매추이(일별)",
    ),
    (
        "domestic.analysis.investor_trend_estimate",
        "/uapi/domestic-stock/v1/quotations/investor-trend-estimate",
        "HHPTJ04160200",
        None,
        (),
        "종목별 외인기관 추정가집계",
    ),
    (
        "domestic.analysis.inquire_daily_trade_volume",
        "/uapi/domestic-stock/v1/quotations/inquire-daily-trade-volume",
        "FHKST03010800",
        None,
        (
            "FID_INPUT_ISCD",
            "FID_INPUT_DATE_1",
            "FID_INPUT_DATE_2",
            "FID_PERIOD_DIV_CODE",
        ),
        "종목별일별매수매도체결량",
    ),
    (
        "domestic.analysis.comp_program_trade_today",
        "/uapi/domestic-stock/v1/quotations/comp-program-trade-today",
        "FHPPG04600101",
        None,
        (
            "FID_MRKT_CLS_CODE",
            "FID_SCTN_CLS_CODE",
            "FID_INPUT_ISCD",
            "FID_COND_MRKT_DIV_CODE1",
            "FID_INPUT_HOUR_1",
        ),
        "프로그램매매 종합현황(시간)",
    ),
    (
        "domestic.analysis.comp_program_trade_daily",
        "/uapi/domestic-stock/v1/quotations/comp-program-trade-daily",
        "FHPPG04600001",
        None,
        ("FID_MRKT_CLS_CODE", "FID_INPUT_DATE_1", "FID_INPUT_DATE_2"),
        "프로그램매매 종합현황(일별)",
    ),
    (
        "domestic.analysis.investor_program_trade_today",
        "/uapi/domestic-stock/v1/quotations/investor-program-trade-today",
        "HHPPG046600C1",
        None,
        ("MRKT_DIV_CLS_CODE",),
        "프로그램매매 투자자매매동향(당일)",
    ),
    (
        "domestic.analysis.daily_credit_balance",
        "/uapi/domestic-stock/v1/quotations/daily-credit-balance",
        "FHPST04760000",
        None,
        ("fid_cond_scr_div_code", "fid_input_iscd", "fid_input_date_1"),
        "국내주식 신용잔고 일별추이",
    ),
    (
        "domestic.analysis.exp_price_trend",
        "/uapi/domestic-stock/v1/quotations/exp-price-trend",
        "FHPST01810000",
        None,
        ("fid_cond_mrkt_div_code", "fid_input_iscd"),
        "국내주식 예상체결가 추이",
    ),
    (
        "domestic.analysis.daily_short_sale",
        "/uapi/domestic-stock/v1/quotations/daily-short-sale",
        "FHPST04830000",
        None,
        ("FID_COND_MRKT_DIV_CODE", "FID_INPUT_ISCD", "FID_INPUT_DATE_1"),
        "국내주식 공매도 일별추이",
    ),
    (
        "domestic.analysis.overtime_exp_trans_fluct",
        "/uapi/domestic-stock/v1/ranking/overtime-exp-trans-fluct",
        "FHKST11860000",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_RANK_SORT_CLS_CODE",
            "FID_DIV_CLS_CODE",
            "FID_INPUT_PRICE_1",
            "FID_INPUT_PRICE_2",
            "FID_INPUT_VOL_1",
        ),
        "국내주식 시간외예상체결등락률",
    ),
    (
        "domestic.analysis.tradprt_byamt",
        "/uapi/domestic-stock/v1/quotations/tradprt-byamt",
        "FHKST111900C0",
        None,
        ("FID_COND_SCR_DIV_CODE", "FID_INPUT_ISCD"),
        "국내주식 체결금액별 매매비중",
    ),
    (
        "domestic.analysis.mktfunds",
        "/uapi/domestic-stock/v1/quotations/mktfunds",
        "FHKST649100C0",
        None,
        (),
        "국내 증시자금 종합",
    ),
    (
        "domestic.analysis.daily_loan_trans",
        "/uapi/domestic-stock/v1/quotations/daily-loan-trans",
        "HHPST074500C0",
        None,
        ("MKSC_SHRN_ISCD", "START_DATE", "END_DATE", "CTS"),
        "종목별 일별 대차거래추이",
    ),
    (
        "domestic.analysis.capture_uplowprice",
        "/uapi/domestic-stock/v1/quotations/capture-uplowprice",
        "FHKST130000C0",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_PRC_CLS_CODE",
            "FID_DIV_CLS_CODE",
            "FID_INPUT_ISCD",
            "FID_TRGT_CLS_CODE",
            "FID_TRGT_EXLS_CLS_CODE",
            "FID_INPUT_PRICE_1",
            "FID_INPUT_PRICE_2",
            "FID_VOL_CNT",
        ),
        "국내주식 상하한가 포착",
    ),
    (
        "domestic.analysis.pbar_tratio",
        "/uapi/domestic-stock/v1/quotations/pbar-tratio",
        "FHPST01130000",
        None,
        ("FID_INPUT_ISCD", "FID_COND_SCR_DIV_CODE", "FID_INPUT_HOUR_1"),
        "국내주식 매물대/거래비중",
    ),
)

for name, path, tr_id_real, tr_id_mock, required_params, _api_name in _SPECS:
    register(
        EndpointSpec(
            name=name,
            method="GET",
            path=path,
            tr_id_real=tr_id_real,
            tr_id_mock=tr_id_mock,
            required_params=required_params,
        )
    )
