"""EndpointSpec registry for `[국내주식] 종목정보.xlsx`."""

from __future__ import annotations

from kis.endpoints.registry import EndpointSpec, register

# Each tuple keeps the source workbook row API 명 in the final field.
_SPECS = (
    (
        "domestic.symbol_info.product_info",
        "/uapi/domestic-stock/v1/quotations/search-info",
        "CTPF1604R",
        None,
        ("PRDT_TYPE_CD",),
        "상품기본조회",
    ),
    (
        "domestic.symbol_info.stock_info",
        "/uapi/domestic-stock/v1/quotations/search-stock-info",
        "CTPF1002R",
        None,
        ("PDNO",),
        "주식기본조회",
    ),
    (
        "domestic.symbol_info.balance_sheet",
        "/uapi/domestic-stock/v1/finance/balance-sheet",
        "FHKST66430100",
        None,
        ("fid_cond_mrkt_div_code", "fid_input_iscd"),
        "국내주식 대차대조표",
    ),
    (
        "domestic.symbol_info.income_statement",
        "/uapi/domestic-stock/v1/finance/income-statement",
        "FHKST66430200",
        None,
        ("fid_cond_mrkt_div_code", "fid_input_iscd"),
        "국내주식 손익계산서",
    ),
    (
        "domestic.symbol_info.financial_ratio",
        "/uapi/domestic-stock/v1/finance/financial-ratio",
        "FHKST66430300",
        None,
        ("fid_cond_mrkt_div_code", "fid_input_iscd"),
        "국내주식 재무비율",
    ),
    (
        "domestic.symbol_info.profit_ratio",
        "/uapi/domestic-stock/v1/finance/profit-ratio",
        "FHKST66430400",
        None,
        ("FID_DIV_CLS_CODE", "fid_cond_mrkt_div_code"),
        "국내주식 수익성비율",
    ),
    (
        "domestic.symbol_info.other_major_ratios",
        "/uapi/domestic-stock/v1/finance/other-major-ratios",
        "FHKST66430500",
        None,
        ("fid_div_cls_code", "fid_cond_mrkt_div_code"),
        "국내주식 기타주요비율",
    ),
    (
        "domestic.symbol_info.stability_ratio",
        "/uapi/domestic-stock/v1/finance/stability-ratio",
        "FHKST66430600",
        None,
        ("fid_div_cls_code", "fid_cond_mrkt_div_code"),
        "국내주식 안정성비율",
    ),
    (
        "domestic.symbol_info.growth_ratio",
        "/uapi/domestic-stock/v1/finance/growth-ratio",
        "FHKST66430800",
        None,
        ("fid_div_cls_code", "fid_cond_mrkt_div_code"),
        "국내주식 성장성비율",
    ),
    (
        "domestic.symbol_info.credit_by_company",
        "/uapi/domestic-stock/v1/quotations/credit-by-company",
        "FHPST04770000",
        None,
        (
            "fid_slct_yn",
            "fid_input_iscd",
            "fid_cond_scr_div_code",
            "fid_cond_mrkt_div_code",
        ),
        "국내주식 당사 신용가능종목",
    ),
    (
        "domestic.symbol_info.dividend",
        "/uapi/domestic-stock/v1/ksdinfo/dividend",
        "HHKDB669102C0",
        None,
        ("GB1", "F_DT", "T_DT", "SHT_CD", "HIGH_GB"),
        "예탁원정보(배당일정)",
    ),
    (
        "domestic.symbol_info.purreq",
        "/uapi/domestic-stock/v1/ksdinfo/purreq",
        "HHKDB669103C0",
        None,
        ("T_DT", "F_DT", "CTS"),
        "예탁원정보(주식매수청구일정)",
    ),
    (
        "domestic.symbol_info.merger_split",
        "/uapi/domestic-stock/v1/ksdinfo/merger-split",
        "HHKDB669104C0",
        None,
        ("F_DT", "T_DT", "SHT_CD"),
        "예탁원정보(합병/분할일정)",
    ),
    (
        "domestic.symbol_info.rev_split",
        "/uapi/domestic-stock/v1/ksdinfo/rev-split",
        "HHKDB669105C0",
        None,
        ("CTS", "F_DT", "T_DT", "MARKET_GB"),
        "예탁원정보(액면교체일정)",
    ),
    (
        "domestic.symbol_info.cap_dcrs",
        "/uapi/domestic-stock/v1/ksdinfo/cap-dcrs",
        "HHKDB669106C0",
        None,
        ("F_DT", "T_DT", "SHT_CD"),
        "예탁원정보(자본감소일정)",
    ),
    (
        "domestic.symbol_info.list_info",
        "/uapi/domestic-stock/v1/ksdinfo/list-info",
        "HHKDB669107C0",
        None,
        ("T_DT", "F_DT", "CTS"),
        "예탁원정보(상장정보일정)",
    ),
    (
        "domestic.symbol_info.pub_offer",
        "/uapi/domestic-stock/v1/ksdinfo/pub-offer",
        "HHKDB669108C0",
        None,
        ("CTS", "F_DT", "T_DT"),
        "예탁원정보(공모주청약일정)",
    ),
    (
        "domestic.symbol_info.forfeit",
        "/uapi/domestic-stock/v1/ksdinfo/forfeit",
        "HHKDB669109C0",
        None,
        ("T_DT", "F_DT", "CTS"),
        "예탁원정보(실권주일정)",
    ),
    (
        "domestic.symbol_info.mand_deposit",
        "/uapi/domestic-stock/v1/ksdinfo/mand-deposit",
        "HHKDB669110C0",
        None,
        ("SHT_CD", "F_DT", "CTS"),
        "예탁원정보(의무예치일정)",
    ),
    (
        "domestic.symbol_info.paidin_capin",
        "/uapi/domestic-stock/v1/ksdinfo/paidin-capin",
        "HHKDB669100C0",
        None,
        ("GB1", "F_DT", "T_DT", "SHT_CD"),
        "예탁원정보(유상증자일정)",
    ),
    (
        "domestic.symbol_info.bonus_issue",
        "/uapi/domestic-stock/v1/ksdinfo/bonus-issue",
        "HHKDB669101C0",
        None,
        ("F_DT", "T_DT", "SHT_CD"),
        "예탁원정보(무상증자일정)",
    ),
    (
        "domestic.symbol_info.sharehld_meet",
        "/uapi/domestic-stock/v1/ksdinfo/sharehld-meet",
        "HHKDB669111C0",
        None,
        ("F_DT", "T_DT", "SHT_CD"),
        "예탁원정보(주주총회일정)",
    ),
    (
        "domestic.symbol_info.estimate_perform",
        "/uapi/domestic-stock/v1/quotations/estimate-perform",
        "HHKST668300C0",
        None,
        (),
        "국내주식 종목추정실적",
    ),
    (
        "domestic.symbol_info.lendable_by_company",
        "/uapi/domestic-stock/v1/quotations/lendable-by-company",
        "CTSC2702R",
        None,
        (
            "PDNO",
            "THCO_STLN_PSBL_YN",
            "INQR_DVSN_1",
            "CTX_AREA_FK200",
            "CTX_AREA_NK100",
        ),
        "당사 대주가능 종목",
    ),
    (
        "domestic.symbol_info.invest_opinion",
        "/uapi/domestic-stock/v1/quotations/invest-opinion",
        "FHKST663300C0",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_INPUT_DATE_1",
            "FID_INPUT_DATE_2",
        ),
        "국내주식 종목투자의견",
    ),
    (
        "domestic.symbol_info.invest_opbysec",
        "/uapi/domestic-stock/v1/quotations/invest-opbysec",
        "FHKST663400C0",
        None,
        (
            "FID_COND_SCR_DIV_CODE",
            "FID_INPUT_ISCD",
            "FID_DIV_CLS_CODE",
            "FID_INPUT_DATE_1",
            "FID_INPUT_DATE_2",
        ),
        "국내주식 증권사별 투자의견",
    ),
)

for name, path, tr_id_real, tr_id_mock, required_params, _api_name in _SPECS:
    register(
        EndpointSpec(
            name=name,
            method="GET",
            path=path,
            tr_id_real=tr_id_real,
            tr_id_mock=tr_id_mock,
            required_params=required_params,
        )
    )
